name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: SCP mycode.php to EC2
      run: |
        scp -i ~/.ssh/id_rsa ./mycode.php ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/home/ubuntu/
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}

    - name: Move mycode.php to /var/www/wordpress
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          sudo mv /home/ubuntu/mycode.php /var/www/wordpress/
          sudo chown www-data:www-data /var/www/wordpress/mycode.php
          sudo chmod 644 /var/www/wordpress/mycode.php
        EOF
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}

    - name: Restart Nginx (if needed)
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} 'sudo systemctl restart nginx'
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}
